FROM eclipse-temurin:21.0.3_9-jre-ubi9-minimal

ARG UID=1001

RUN adduser -u $UID ilivalidator 

WORKDIR /work
RUN chown $UID:0 . && \
    chmod 0775 . && \
    ls -la

ENV HOME=/ilivalidator
WORKDIR $HOME

COPY target/ilivalidator-web-service-server-*.jar ./application.jar
RUN chown $UID:0 . && \
    chmod 0775 . && \
    ls -la

USER $UID
EXPOSE 8080

ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true
CMD java -XX:+UseParallelGC -XX:MaxRAMPercentage=80.0 -jar application.jar --spring.profiles.active=docker